version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server  # Adjust as necessary
    ports:
      - "5000:5000"

  client:
    build:
      context: .
      dockerfile: Dockerfile.client  # Adjust as necessary
    depends_on:
      - server
