# Use the official Python image as a base
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy all neccesary files to the working directory
COPY requirements.txt /app/requirements.txt
COPY utilities /app/utilities
COPY assets /app/assets
COPY src /app/src

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port the server will run on
EXPOSE 5000

# Run the application
CMD ["python", "src/client/client.py"]