# Use the official ubuntu/postgres image as the base image
FROM ubuntu/postgres:latest AS environment

# Update package list and install Python, pip, and other tools you need
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-dev \
    build-essential \
    curl \
    git \
    vim \
    net-tools